hydra:
  run:
    # Configure output dir of each experiment programmatically from the arguments
    # Example "outputs/mnist/classifier/baseline/2021-03-10-141516"
    dir: outputs/${data.dataset.name}/${data.dataset.data_type}_${data.dataset.encoding}/${models.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - accelerator
          - models.name
          - data.dataset.name
          - data.dataset.data_type
          - data.dataset.encoding
          - run_name
          - models
    chdir: true

# Global configurations shared between different modules
run_name: change_me
seed: 20211201
accelerator: gpu
num_devices: 1
num_cpus: 16
epochs: 10

defaults:
  - data/data_generation: gridworlds
  - data/dataset: gridworlds
  - models: graphVAE
  - optim: adam
  - results: graphVAE
  - _self_

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  # Hydra's launcher API is synchronous and not async
  # https://github.com/facebookresearch/hydra/issues/1377#issuecomment-773583397
  # so all jobs in a batch must finish before launching next batch
  #
  # Refer to https://hydra.cc/docs/plugins/submitit_launcher/ and
  # https://github.com/facebookincubator/submitit/blob/main/docs/examples.md
  # for more information.
  #
  # Use submitit_local for local multiprocessing
#  - override /hydra/launcher: submitit_local
#  - override /hydra/sweeper: wandb
